/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2016-09-26 06:57:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.bucketList;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class post_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/bc/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/BucketTree/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1472260418994L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t<div class=\"x_panel\">\r\n");
      out.write("\t\t\t\t<div class=\"right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"x_title\">\r\n");
      out.write("\t\t\t\t\t<h2>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bucket.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h2>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"x_title_m\">\r\n");
      out.write("\t\t\t\t\t<span class=\"post_writer\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bucket.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span> <span class=\"post_date\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bucket.date }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"right\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"tag\">20대</span> <span class=\"tag\">혼자</span> <span\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"tag\">여행</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"x_content\">\r\n");
      out.write("\t\t\t\t\t\t");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bucket.contents}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- 작업일지 부분 -->\r\n");
      out.write("\t\t\t<div class=\"box box-default collapsed-box\">\r\n");
      out.write("\t\t\t\t<div class=\"box-header withorder\">\r\n");
      out.write("\t\t\t\t\t<h3 class=\"box-title\">Timeline</h3>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"box-tools pull-right\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-box-tool\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-toggle=\"collapse\" data-target=\"#collapseTimeline\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"fa fa-plus\"></i>\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- /.box-tools -->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- /.box-header -->\r\n");
      out.write("\t\t\t\t<div class=\"collapse\" id=\"collapseTimeline\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"timeline\">\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"timeline-badge\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"timeline-panel\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"timeline-heading\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h4 class=\"timeline-title\">첫번째일지</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<small class=\"text-muted\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-time\"></i> 2016.08.26 11:14</small>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"timeline-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span>Lorem ipsum dolor sit amet, consectetur adipiscing\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\telit, sed do eiusmod tempor incididunt ut labore et dolore\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tmagna aliqua. Ut enim ad minim veniam, quis nostrud\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\texercitation ullamco laboris nisi ut aliquip ex ea commodo\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tconsequat.</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"timeline-footer\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a class=\"btn btn-default\" title=\"수정\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-pencil\"></i></a> <a class=\"btn btn-default\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttitle=\"삭제\"><i class=\"fa fa-trash-o\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"timeline-inverted\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"timeline-badge\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"timeline-panel\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"timeline-heading\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h4 class=\"timeline-title\">두번쨰일지</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<small class=\"text-muted\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-time\"></i> 2016.08.26 11:14</small>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"timeline-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<img src=\"/kr/resources/img/photo1.png\" class=\"timeline-img\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\talign=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</p> \"Duis aute irure dolor in reprehenderit in voluptate velit\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tesse cillum dolore eu fugiat nulla pariatur. Excepteur sint\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\toccaecat cupidatat non proident, sunt in culpa qui officia\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdeserunt mollit anim id est laborum.\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"timeline-footer\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a class=\"btn btn-default\" title=\"수정\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-pencil\"></i></a> <a class=\"btn btn-default\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttitle=\"삭제\"><i class=\"fa fa-trash-o\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"timeline-badge\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"timeline-panel\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"timeline-heading\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h4 class=\"timeline-title\">세번째일지</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<small class=\"text-muted\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-time\"></i> 2016.08.26 11:14</small>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"timeline-body\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<img src=\"/kr/resources/img/photo2.jpg\" class=\"timeline-img\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\talign=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</p> 정당은 그 목적·조직과 활동이 민주적이어야 하며, 국민의 정치적 의사형성에 참여하는데 필요한 조직을 가져야\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t한다. 이 헌법중 공무원의 임기 또는 중임제한에 관한 규정은 이 헌법에 의하여 그 공무원이 최초로 선출 또는\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t임명된 때로부터 적용한다. 국회나 그 위원회의 요구가 있을 때에는 국무총리·국무위원 또는 정부위원은\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t출석·답변하여야 하며, 국무총리 또는 국무위원이 출석요구를 받은 때에는 국무위원 또는 정부위원으로 하여금\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t출석·답변하게 할 수 있다.\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"timeline-footer\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a class=\"btn btn-default\" title=\"수정\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-pencil\"></i></a> <a class=\"btn btn-default\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttitle=\"삭제\"><i class=\"fa fa-trash-o\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"timeline-inverted\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"timeline-badge\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"timeline-panel\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"timeline-heading\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h4 class=\"timeline-title\">네번째일지</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<small class=\"text-muted\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-time\"></i> 2016.08.26 11:14</small>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"timeline-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span>대법원장의 임기는 6년으로 하며, 중임할 수 없다. 국무회의는 대통령·국무총리와 15인\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t이상 30인 이하의 국무위원으로 구성한다. 국가안전보장에 관련되는 대외정책·군사정책과 국내정책의 수립에 관하여\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t국무회의의 심의에 앞서 대통령의 자문에 응하기 위하여 국가안전보장회의를 둔다.</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"timeline-footer\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a class=\"btn btn-default\" title=\"수정\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-pencil\"></i></a> <a class=\"btn btn-default\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttitle=\"삭제\"><i class=\"fa fa-trash-o\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"timeline-badge\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"timeline-panel\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"timeline-heading\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h4 class=\"timeline-title\">다섯번째일지</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<small class=\"text-muted\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-time\"></i> 2016.08.26 11:14</small>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"timeline-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span>법률안에 이의가 있을 때에는 대통령은 제1항의 기간내에 이의서를 붙여 국회로 환부하고, 그\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t재의를 요구할 수 있다. 국회의 폐회중에도 또한 같다. 국방상 또는 국민경제상 긴절한 필요로 인하여 법률이\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t정하는 경우를 제외하고는, 사영기업을 국유 또는 공유로 이전하거나 그 경영을 통제 또는 관리할 수 없다.</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"timeline-footer\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a class=\"btn btn-default\" title=\"수정\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-pencil\"></i></a> <a class=\"btn btn-default\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttitle=\"삭제\"><i class=\"fa fa-trash-o\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"timeline-inverted\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"timeline-badge \"></div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"timeline-panel\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"timeline-heading\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h4 class=\"timeline-title\">여섯번째일지</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<small class=\"text-muted\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-time\"></i> 2016.08.26 11:14</small>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"timeline-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span>헌법재판소의 장은 국회의 동의를 얻어 재판관중에서 대통령이 임명한다. 정부는 회계연도마다\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t예산안을 편성하여 회계연도 개시 90일전까지 국회에 제출하고, 국회는 회계연도 개시 30일전까지 이를 의결하여야\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t한다.</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"timeline-footer\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a class=\"btn btn-default\" title=\"수정\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-pencil\"></i></a> <a class=\"btn btn-default\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttitle=\"삭제\"><i class=\"fa fa-trash-o\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"timeline-badge\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"timeline-panel\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"timeline-heading\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h4 class=\"timeline-title\">일곱번째 일지</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<small class=\"text-muted\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-time\"></i> 2016.08.26 11:14</small>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"timeline-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span>대통령은 법률안의 일부에 대하여 또는 법률안을 수정하여 재의를 요구할 수 없다.</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"timeline-footer\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a class=\"btn btn-default\" title=\"수정\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-pencil\"></i></a> <a class=\"btn btn-default\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttitle=\"삭제\"><i class=\"fa fa-trash-o\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"timeline-inverted\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"timeline-badge\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"timeline-panel\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"timeline-heading\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h4 class=\"timeline-title\">여덟번째 일지</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<small class=\"text-muted\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-time\"></i> 2016.08.26 11:14</small>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"timeline-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span>모든 국민은 통신의 비밀을 침해받지 아니한다. 공무원인 근로자는 법률이 정하는 자에 한하여\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t단결권·단체교섭권 및 단체행동권을 가진다.</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"timeline-footer\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a class=\"btn btn-default\" title=\"수정\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-pencil\"></i></a> <a class=\"btn btn-default\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttitle=\"삭제\"><i class=\"fa fa-trash-o\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"timeline-badge\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"timeline-panel\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"timeline-heading\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h4 class=\"timeline-title\">아홉번째 일지</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<small class=\"text-muted\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-time\"></i> 2016.08.26 11:14</small>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"timeline-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span>예비비는 총액으로 국회의 의결을 얻어야 한다. 예비비의 지출은 차기국회의 승인을 얻어야\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t한다. 국회의원이 회기전에 체포 또는 구금된 때에는 현행범인이 아닌 한 국회의 요구가 있으면 회기중 석방된다.\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t누구든지 체포 또는 구속을 당한 때에는 적부의 심사를 법원에 청구할 권리를 가진다. 국민의 모든 자유와 권리는\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t국가안전보장·질서유지 또는 공공복리를 위하여 필요한 경우에 한하여 법률로써 제한할 수 있으며, 제한하는 경우에도\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t자유와 권리의 본질적인 내용을 침해할 수 없다.</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"timeline-footer\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a class=\"btn btn-default\" title=\"수정\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-pencil\"></i></a> <a class=\"btn btn-default\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttitle=\"삭제\"><i class=\"fa fa-trash-o\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"timeline-inverted\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"timeline-badge\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"timeline-panel\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"timeline-heading\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h4 class=\"timeline-title\">열번째일지</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<small class=\"text-muted\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-time\"></i> 2016.08.26 11:14</small>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"timeline-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span>선거에 관한 경비는 법률이 정하는 경우를 제외하고는 정당 또는 후보자에게 부담시킬 수\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t없다. 대통령은 국무총리·국무위원·행정각부의 장 기타 법률이 정하는 공사의 직을 겸할 수 없다.</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"timeline-footer\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a class=\"btn btn-default\" title=\"수정\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-pencil\"></i></a> <a class=\"btn btn-default\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttitle=\"삭제\"><i class=\"fa fa-trash-o\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- /작업일지 부분 -->\r\n");
      out.write("\t\t\t<!-- 댓글 부분 -->\r\n");
      out.write("\t\t\t<div class=\"box box-default collapsed-box\">\r\n");
      out.write("\t\t\t\t<div class=\"box-header withorder\">\r\n");
      out.write("\t\t\t\t\t<h3 class=\"box-title\">Comments</h3>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"box-tools pull-right\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-box-tool\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-toggle=\"collapse\" data-target=\"#collapseComment\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"fa fa-plus\"></i>\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- /.box-tools -->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- /.box-header -->\r\n");
      out.write("\t\t\t\t<div class=\"collapse\" id=\"collapseComment\">\r\n");
      out.write("\t\t\t\t\t<div class=\"box-footer box-comments\">\r\n");
      out.write("\t\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- /.box-footer -->\r\n");
      out.write("\t\t\t\t\t<div class=\"box-footer\">\r\n");
      out.write("\t\t\t\t\t\t<form method=\"post\" id=\"formData\" name=\"formData\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"img-push\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" name=\"comment\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"input-group-btn\" id=\"comment\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-default\" id=\"addComment\" data-idx=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bucket.idx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">등록</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" name=\"bidx\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bucket.idx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t<input name=\"author\" type=\"checkbox\" id=\"check\" value=1>작성자만 보기</input>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- /댓글 부분 -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("$(document).on('click', '#addComment', function(){\r\n");
      out.write("\talert('에이젝스 돌입')\r\n");
      out.write("\tvar formData =$('#formData').serialize();\r\n");
      out.write("\tvar str='';\r\n");
      out.write("\talert(formData)\r\n");
      out.write("\tjQuery.ajax({\r\n");
      out.write("\t\t\r\n");
      out.write("\t\turl : \"/BucketTree/bucketList/addCommentRequestAjax\",\r\n");
      out.write("\t\ttype : \"POST\",\r\n");
      out.write("\t\tdata : formData,\r\n");
      out.write("\t\tcache: false,\r\n");
      out.write("\t\tsuccess :  function(data) {\r\n");
      out.write("\t\t\tif(data !=\"\"){\r\n");
      out.write("\t\t\t\t$(data).each(\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\tfunction(){\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tstr+='<div class=\"box-comment\" data-idx=\"'+this.idx+'\">'\r\n");
      out.write("\t\t\t\t\t+'<img src=\"/kr/resources/img/user1-128x128.jpg\" class=\"user-image\" alt=\"User Image\">'\r\n");
      out.write("\t\t\t\t\t+'<div class=\"comment-text\">'\r\n");
      out.write("\t\t\t\t\t+'<span class=\"username\">'+this.name+'<a href=\"\" id=\"cedit\" style=\"margin-left:790px\">수정</a><a href=\"\" id=\"cdelete\" style=\"margin-left:10px\">삭제</a><span class=\"text-muted pull-right post_date\">'+this.date+'</span></span>'\r\n");
      out.write("\t\t\t\t\t+ this.contents\r\n");
      out.write("\t\t\t\t\t+'</div>'\r\n");
      out.write("\t\t\t\t\t+'</div>';      \t\t\t\t\t    \r\n");
      out.write("\t\t\t\t}\t\t\r\n");
      out.write("\t\t\t\t)  \r\n");
      out.write("\t\t\t\t  $('.box-footer.box-comments').append(str);\r\n");
      out.write("\t\t\t\t  $('#addComment').val(\"\");\r\n");
      out.write("\t\t\t\t  }else\r\n");
      out.write("\t\t\t\t\t  alert('불러올 데이터가 없습니다')\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$(document).on('click', '#cdelete', function(){\r\n");
      out.write("\tvar evnetTarget = this;\r\n");
      out.write("\tvar eventIdx = $(this).attr('data-idx');\r\n");
      out.write("\talert(eventIdx)\r\n");
      out.write("\tjQuery.ajax({\r\n");
      out.write("\t\tmethod :\"POST\",\r\n");
      out.write("\t\turl : \"/BucketTree/bucketList/deleteCommentRequestAjax\",\r\n");
      out.write("\t\ttype : \"JSON\",\r\n");
      out.write("\t\tdata : {\r\n");
      out.write("\t\t\tcommentIdx : eventIdx,\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\tsuccess :  function(data) {\r\n");
      out.write("\t\t\tif(data==true){\r\n");
      out.write("\t\t\t\t$('div').remove('#'+eventIdx)\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$(document).on('click', '#cedit', function(){\r\n");
      out.write("\talert('도착')\r\n");
      out.write("\tvar evnetTarget = this;\r\n");
      out.write("\tvar eventIdx = $(this).attr('data-idx');\r\n");
      out.write("\tvar eventIdx2 = '#c'+eventIdx;\r\n");
      out.write("\tvar eventDiv = '#d'+eventIdx;\r\n");
      out.write("\r\n");
      out.write("\tvar content =document.getElementById(eventIdx2);\r\n");
      out.write("\talert(cotent)\r\n");
      out.write("\tvar content2 = $(content).html();\r\n");
      out.write("\talert(content2)\r\n");
      out.write("\t$(eventDiv).append('<textarea>'+content2+'</textarea>');\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f0.setParent(null);
    // /WEB-INF/views/bucketList/post.jsp(11,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setVar("check");
    // /WEB-INF/views/bucketList/post.jsp(11,5) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/bucketList/post.jsp(11,5) '${check.idx}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${check.idx}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
    if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f1.setParent(null);
    // /WEB-INF/views/bucketList/post.jsp(12,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f1.setVar("check2");
    // /WEB-INF/views/bucketList/post.jsp(12,5) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/bucketList/post.jsp(12,5) '${bucket.user_idx}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${bucket.user_idx}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
    if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /WEB-INF/views/bucketList/post.jsp(13,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${check eq check2}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t    <button class=\"btn btn-default\" title=\"수정\" onclick=\"location.href='/BucketTree/bucketList/");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bucket.idx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("/edit.do'\">\r\n");
        out.write("\t\t\t\t\t\t<i class=\"fa fa-pencil\"></i>\r\n");
        out.write("\t\t\t\t\t\t</button>\r\n");
        out.write("\t\t\t\t\t    <button class=\"btn btn-default\" title=\"삭제\" onclick=\"location.href='/BucketTree/bucketList/");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bucket.idx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("/delete.do'\">\r\n");
        out.write("\t\t\t\t\t\t<i class=\"fa fa-trash-o\"></i>\r\n");
        out.write("\t\t\t\t\t</button>\r\n");
        out.write("\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /WEB-INF/views/bucketList/post.jsp(321,6) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/bucketList/post.jsp(321,6) '${clist}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${clist}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /WEB-INF/views/bucketList/post.jsp(321,6) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("CommentVO");
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t<div class=\"box-comment\" id=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${CommentVO.idx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("\t\t\t\t\t\t\t<!-- User image -->\r\n");
          out.write("\t\t\t\t\t\t\t<img src=\"/kr/resources/img/user1-128x128.jpg\" class=\"user-image\"\r\n");
          out.write("\t\t\t\t\t\t\t\talt=\"User Image\">\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t<div class=\"comment-text\" id=d");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${CommentVO.idx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(">\r\n");
          out.write("\t\t\t\t\t\t\t\t<span class=\"username\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${CommentVO.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("<a id=\"cedit\" style=\"margin-left:790px\" data-idx=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${CommentVO.idx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">수정</a><a id=\"cdelete\" style=\"margin-left:10px\" data-idx=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${CommentVO.idx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">삭제</a><span\r\n");
          out.write("\t\t\t\t\t\t\t\t\tclass=\"text-muted pull-right post_date\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${CommentVO.date }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</span>\r\n");
          out.write("\t\t\t\t\t\t\t\t</span>\r\n");
          out.write("\t\t\t\t\t\t\t\t<!-- /.username -->\r\n");
          out.write("\t\t\t\t\t\t\t\t<span id=c");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${CommentVO.idx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${CommentVO.contents}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</span>\r\n");
          out.write("\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t\t<!-- /.comment-text -->\r\n");
          out.write("\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }
}
