/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2016-09-26 06:48:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.include;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/bc/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/BucketTree/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1472260418994L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<title>Home</title>\r\n");
      out.write(" <!-- JQUERY 2.2.3 -->\r\n");
      out.write("<script src=\"http://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.2.3.min.js\"></script>\r\n");
      out.write("<!-- jQuery UI CSS파일 --> \r\n");
      out.write("<link rel=\"stylesheet\" href=\"http://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css\" type=\"text/css\" />\r\n");
      out.write("<!--  jQuery UI 라이브러리 js파일 -->\r\n");
      out.write("<script   src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.js\"></script>\r\n");
      out.write("<!-- CSS -->\r\n");
      out.write(" <!-- bootstrap 3.3.7 -->\r\n");
      out.write("<link href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("<link href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css\" rel=\"stylesheet\">\r\n");
      out.write(" <!-- font-awesome 4.5.0 -->\r\n");
      out.write("<link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write(" <!-- ionicons 2.0.1 -->\r\n");
      out.write("<link href=\"https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css\" rel=\"stylesheet\"\t>\r\n");
      out.write("<!-- sock.js -->\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/sockjs-client/1.1.1/sockjs.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- COMMON -->\r\n");
      out.write("<link href=\"/BucketTree/css/common.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<!-- MENU CSS -->\r\n");
      out.write("<link href=\"/BucketTree/css/menu.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<!-- LOGIN CSS-->\t\r\n");
      out.write("<link href=\"/BucketTree/css/login.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<!-- SIDEBAR CSS-->\r\n");
      out.write("<link href=\"/BucketTree/css/sidebar.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<!-- CHAT_POPUP -->\r\n");
      out.write("<link href=\"/BucketTree/css/chat_popup.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<!-- FRIREND LIST -->\r\n");
      out.write("<link href=\"/BucketTree/css/friendlist.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<!-- BUCKETLIST -->\r\n");
      out.write("<link href=\"/BucketTree/css/bucketList.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<!-- TIMELINE -->\r\n");
      out.write("<link href=\"/BucketTree/css/timeline.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<!-- BUCKET WRITE -->\r\n");
      out.write("<link href=\"/BucketTree/css/bucketWrite.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\r\n");
      out.write("<!-- MENU JS-->\r\n");
      out.write("<script type=\"text/javascript\"\tsrc=\"/BucketTree/js/menu/modernizr.custom.js\"></script>\r\n");
      out.write("<!--MENU -->\r\n");
      out.write("<script src=\"/BucketTree/js/sidebar/sidebar.js\"></script>\r\n");
      out.write("<!-- CHAT-->\r\n");
      out.write("<script type=\"text/javascript\"\tsrc=\"/BucketTree/js/chat/chat.js\"></script>\r\n");
      out.write("<!-- BUCKETLIST -->\r\n");
      out.write("<script type=\"text/javascript\"\tsrc=\"/BucketTree/js/bucketList/bucketList.js\"></script>\r\n");
      out.write("<!-- BUCKETLIST_SELELCTBOX -->\r\n");
      out.write("<script type=\"text/javascript\"\tsrc=\"/BucketTree/js/bucketList/selectbox.js\"></script>\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write(" <!-- SMART EDITOR -->\r\n");
      out.write("<script type=\"text/javascript\"\tsrc=\"/BucketTree/se2/init.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\tsrc=\"/BucketTree/se2/js/HuskyEZCreator.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
